version: "3.9"

services:
  app:
    container_name: chatfly_admin
    build: .
    restart: always
    ports:
      - "3001:3001"
    healthcheck:
      test: [ "CMD-SHELL", "curl http://0.0.0.0:3001/" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chatfly_network

networks:
  chatfly_network:
    name: chatfly_network
    driver: bridge