name: Main Docker Compose CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create env
        env:
          SOURCE_DIRECTORY: "~/chatfly/chatfly-be"
        run: |
          echo ${{ vars.MAIN_ENV }} >> $SOURCE_DIRECTORY/.env

      - name: Build and run all docker compose
        run: docker-compose up --build -d
